-- Seed/Sync cards catalog from prisma/cards.csv
INSERT INTO "Cards" ("id", "type", "element", "hp", "name", "cap1", "cap2", "prize", "retreat", "weakness", "resist", "deckId") VALUES
('card_001', 'pokemon', 'dark', 110, 'absol', 'allure', 'dark_cutter', 1, 1, 'grass', NULL, NULL),
('card_002', 'pokemon', 'psy', 90, 'alcremie', 'sweet_circle', NULL, 1, 1, 'metal', NULL, NULL),
('card_003', 'supporter', NULL, NULL, 'brock_scouting', 'brock_scouting_cap', NULL, NULL, NULL, NULL, NULL, NULL),
('card_004', 'pokemon', 'fire', 140, 'ceruledge', 'infernal slash', NULL, 1, 2, 'water', NULL, NULL),
('card_005', 'pokemon', 'fire', 70, 'charcadet', 'gather strength', 'chop', 1, 2, 'water', NULL, NULL),
('card_006', 'supporter', NULL, NULL, 'dawn', 'dawn_cap', NULL, NULL, NULL, NULL, NULL, NULL),
('card_007', 'supporter', NULL, NULL, 'drayton', 'drayton_cap', NULL, NULL, NULL, NULL, NULL, NULL),
('card_008', 'item', NULL, NULL, 'dusk_ball', 'dusk_ball_cap', NULL, NULL, NULL, NULL, NULL, NULL),
('card_009', 'item', NULL, NULL, 'energy_recycler', 'energy_recycler_cap', NULL, NULL, NULL, NULL, NULL, NULL),
('card_010', 'item', NULL, NULL, 'energy_retrieval', 'energy_retrieval_cap', NULL, NULL, NULL, NULL, NULL, NULL),
('card_011', 'item', NULL, NULL, 'fighting_gong', 'fighting_gong_cap', NULL, NULL, NULL, NULL, NULL, NULL),
('card_012', 'supporter', NULL, NULL, 'firebreather', 'firebreather_cap', NULL, NULL, NULL, NULL, NULL, NULL),
('card_013', 'pokemon', 'combat', 150, 'flygon', 'sandy_flapping', 'cutting_wind', 1, 1, 'grass', NULL, NULL),
('card_014', 'pokemon', 'combat', 70, 'gligar', 'poison_jab', NULL, 1, 1, 'grass', NULL, NULL),
('card_015', 'pokemon', 'combat', 120, 'gliscor', 'poison_ring', NULL, 1, 1, 'grass', NULL, NULL),
('card_016', 'supporter', NULL, NULL, 'grimsley_move', 'grimsley_move_cap', NULL, NULL, NULL, NULL, NULL, NULL),
('card_017', 'supporter', NULL, NULL, 'hilda', 'hilda_cap', NULL, NULL, NULL, NULL, NULL, NULL),
('card_018', 'supporter', NULL, NULL, 'iris_fighting_spirit', 'iris_fighting_spirit_cap', NULL, NULL, NULL, NULL, NULL, NULL),
('card_019', 'pokemon', 'dark', 100, 'krokorok', 'bite', 'confront', 1, 2, 'grass', NULL, NULL),
('card_020', 'pokemon', 'dark', 170, 'krookodile', 'vengeful_fang', 'hammer_in', 1, 3, 'grass', NULL, NULL),
('card_021', 'supporter', NULL, NULL, 'lillie_determination', 'lillie_determination_cap', NULL, NULL, NULL, NULL, NULL, NULL),
('card_022', 'pokemon', 'psy', 50, 'milcery', 'draining_kiss', NULL, 1, 1, 'metal', NULL, NULL),
('card_023', 'pokemon', 'psy', 70, 'mimikyu', 'call_for_family_mimikyu', 'scratch', 1, 1, 'metal', NULL, NULL),
('card_024', 'pokemon', 'fire', 120, 'moltres', 'fighting_wing', NULL, 1, 1, 'water', NULL, NULL),
('card_025', 'item', NULL, NULL, 'premium_power_pro', 'premium_power_pro_cap', NULL, NULL, NULL, NULL, NULL, NULL),
('card_026', 'item', NULL, NULL, 'rare_candy', 'rare_candy_cap', NULL, NULL, NULL, NULL, NULL, NULL),
('card_027', 'pokemon', 'dark', 70, 'sandile', 'ram', 'rear_kick', 1, 2, 'grass', NULL, NULL),
('card_028', 'item', NULL, NULL, 'switch', 'switch_cap', NULL, NULL, NULL, NULL, NULL, NULL),
('card_029', 'pokemon', 'dark', 70, 'toxel', 'call_for_family_toxel', 'playful_kick', 1, 1, 'combat', NULL, NULL),
('card_030', 'pokemon', 'dark', 140, 'toxtricity', 'sinister_surge', 'gentle_slap', 1, 2, 'combat', NULL, NULL),
('card_031', 'pokemon', 'combat', 70, 'trapinch', 'double_headbutt', NULL, 1, 1, 'grass', NULL, NULL),
('card_032', 'item', NULL, NULL, 'ultra_ball', 'ultra_ball_cap', NULL, NULL, NULL, NULL, NULL, NULL),
('card_033', 'pokemon', 'combat', 90, 'vibrava', 'super_vibration', NULL, 1, 1, 'grass', NULL, NULL),
('card_034', 'item', NULL, NULL, 'wondrous_patch', 'wondrous_patch_cap', NULL, NULL, NULL, NULL, NULL, NULL),
('card_035', 'pokemon', 'psy', 130, 'zacian', 'limit_break', NULL, 1, 2, 'metal', NULL, NULL)
ON CONFLICT ("id") DO UPDATE SET
  "type" = EXCLUDED."type",
  "element" = EXCLUDED."element",
  "hp" = EXCLUDED."hp",
  "name" = EXCLUDED."name",
  "cap1" = EXCLUDED."cap1",
  "cap2" = EXCLUDED."cap2",
  "prize" = EXCLUDED."prize",
  "retreat" = EXCLUDED."retreat",
  "weakness" = EXCLUDED."weakness",
  "resist" = EXCLUDED."resist",
  "deckId" = EXCLUDED."deckId";
