import type { CharacterData, PlayerResources } from "@/components/organisms/characters/types";

export const CHARACTERS: CharacterData[] = [
  {
    id: "archer-1",
    name: "Archer",
    portrait: "/heroes/Avatar_Uvhash.webp",
    body: "/heroes/Uvhash.webp",
    baseStats: {
      physicalDamage: 165,
      magicalDamage: 45,
      critChance: 12,
      critDamage: 175,
      hp: 1240,
      mp: 180,
      physicalResistance: 12,
      magicalResistance: 8,
      speed: 118,
    },
    level: 12,
    xpPercent: 67,
    levelUpCost: 450,
    skills: [
      {
        id: "s1",
        name: "Piercing Shot",
        image: "/spells/water_spell.png",
        description: "Deals {physical damage * 1.2 + skill level * 15} physical damage to a single target. Ignores 15% resistance.",
        unlockLevel: 1,
        level: 4,
        cost: 8,
      },
      {
        id: "s2",
        name: "Rain of Arrows",
        image: "/spells/attack_boost2.png",
        description: "Deals {physical damage * 0.8 + skill level * 10} physical damage to all enemies.",
        unlockLevel: 5,
        level: 3,
        cost: 12,
      },
      {
        id: "s3",
        name: "Precision Focus",
        image: "/spells/stunned.png",
        description: "Increases Crit Chance by {5 + skill level * 2}% and Crit Damage by {skill level * 8}% for 3 turns.",
        unlockLevel: 10,
        level: 2,
        cost: 15,
      },
    ],
    stats: {
      physicalDamage: 245,
      magicalDamage: 68,
      critChance: 22,
      critDamage: 215,
      hp: 1680,
      mp: 245,
      physicalResistance: 18,
      magicalResistance: 13,
      speed: 138,
    },
  },
  {
    id: "assassin-1",
    name: "Assassin",
    portrait: "/heroes/Avatar_Wanda.webp",
    body: "/heroes/Wanda.webp",
    baseStats: {
      physicalDamage: 195,
      magicalDamage: 35,
      critChance: 18,
      critDamage: 200,
      hp: 1080,
      mp: 150,
      physicalResistance: 10,
      magicalResistance: 6,
      speed: 128,
    },
    level: 14,
    xpPercent: 34,
    levelUpCost: 580,
    skills: [
      {
        id: "s1",
        name: "Shadow Strike",
        image: "/spells/silenced.png",
        description: "Deals {physical damage * 1.5 + skill level * 20} physical damage. Damage increased by 30% if target HP is below 50%.",
        unlockLevel: 1,
        level: 5,
        cost: 10,
      },
      {
        id: "s2",
        name: "Venom Blade",
        image: "/spells/poison_dagger.png",
        description: "Deals {physical damage * 0.9 + skill level * 12} damage and applies Poison for 3 turns: {skill level * 8} damage per turn.",
        unlockLevel: 6,
        level: 3,
        cost: 14,
      },
      {
        id: "s3",
        name: "Phantom Step",
        image: "/spells/frenzy_spell_(critical_booster).png",
        description: "Grants Invisibility for {1 + Math.floor(skill level / 3)} turn(s). Next attack deals +{skill level * 15}% damage.",
        unlockLevel: 12,
        level: 2,
        cost: 18,
      },
    ],
    stats: {
      physicalDamage: 312,
      magicalDamage: 58,
      critChance: 31,
      critDamage: 268,
      hp: 1420,
      mp: 205,
      physicalResistance: 15,
      magicalResistance: 10,
      speed: 158,
    },
  },
  {
    id: "healer-1",
    name: "Healer",
    portrait: "/heroes/Avatar_Tulu.webp",
    body: "/heroes/Tulu.webp",
    baseStats: {
      physicalDamage: 65,
      magicalDamage: 155,
      critChance: 8,
      critDamage: 150,
      hp: 1380,
      mp: 320,
      physicalResistance: 9,
      magicalResistance: 14,
      speed: 95,
    },
    level: 11,
    xpPercent: 82,
    levelUpCost: 380,
    skills: [
      {
        id: "s1",
        name: "Healing Light",
        image: "/spells/healing_spell.png",
        description: "Restores {magical damage * 0.6 + skill level * 25} HP to a single ally.",
        unlockLevel: 1,
        level: 4,
        cost: 10,
      },
      {
        id: "s2",
        name: "Sanctuary",
        image: "/spells/defense_boost.png",
        description: "Heals all allies for {magical damage * 0.4 + skill level * 15} HP and grants +{skill level * 3}% defense for 2 turns.",
        unlockLevel: 7,
        level: 2,
        cost: 18,
      },
      {
        id: "s3",
        name: "Divine Protection",
        image: "/spells/divine_protection_spell.png",
        description: "Target ally becomes immune to all damage for {1 + Math.floor(skill level / 4)} turn(s).",
        unlockLevel: 14,
        level: 2,
        cost: 35,
      },
    ],
    stats: {
      physicalDamage: 92,
      magicalDamage: 238,
      critChance: 12,
      critDamage: 178,
      hp: 1860,
      mp: 445,
      physicalResistance: 13,
      magicalResistance: 20,
      speed: 118,
    },
  },
  {
    id: "knight-1",
    name: "Knight",
    portrait: "/heroes/Avatar_Sorel.webp",
    body: "/heroes/Sorel.webp",
    baseStats: {
      physicalDamage: 145,
      magicalDamage: 55,
      critChance: 10,
      critDamage: 155,
      hp: 2180,
      mp: 120,
      physicalResistance: 20,
      magicalResistance: 12,
      speed: 88,
    },
    level: 15,
    xpPercent: 56,
    levelUpCost: 720,
    skills: [
      {
        id: "s1",
        name: "Shield Bash",
        image: "/spells/fortify_spell.png",
        description: "Deals {physical damage * 1.1 + skill level * 18} damage and has a {20 + skill level * 3}% chance to Stun for 1 turn.",
        unlockLevel: 1,
        level: 5,
        cost: 12,
      },
      {
        id: "s2",
        name: "Iron Will",
        image: "/spells/attack_boost.png",
        description: "Taunts all enemies and reduces damage taken by {10 + skill level * 4}% for 2 turns.",
        unlockLevel: 5,
        level: 4,
        cost: 15,
      },
      {
        id: "s3",
        name: "Last Stand",
        image: "/spells/on_fire_(burning).png",
        description: "When HP drops below 30%, automatically gain a shield of {max HP * (0.15 + skill level * 0.03)}. Once per battle.",
        unlockLevel: 15,
        level: 2,
        cost: 25,
      },
    ],
    stats: {
      physicalDamage: 218,
      magicalDamage: 88,
      critChance: 16,
      critDamage: 192,
      hp: 2860,
      mp: 175,
      physicalResistance: 29,
      magicalResistance: 18,
      speed: 108,
    },
  },
  {
    id: "mage-1",
    name: "Mage",
    portrait: "/heroes/Avatar_Thais.webp",
    body: "/heroes/Thais.webp",
    baseStats: {
      physicalDamage: 55,
      magicalDamage: 185,
      critChance: 15,
      critDamage: 180,
      hp: 980,
      mp: 380,
      physicalResistance: 7,
      magicalResistance: 16,
      speed: 102,
    },
    level: 13,
    xpPercent: 45,
    levelUpCost: 520,
    skills: [
      {
        id: "s1",
        name: "Fireball",
        image: "/spells/fire_spell.png",
        description: "Deals {magical damage * 1.3 + skill level * 18} fire damage to a single target. 30% chance to apply Burn.",
        unlockLevel: 1,
        level: 5,
        cost: 12,
      },
      {
        id: "s2",
        name: "Arcane Missiles",
        image: "/spells/mana_replenish.png",
        description: "Launches {2 + Math.floor(skill level / 3)} missiles, each dealing {magical damage * 0.5} damage. Targets random enemies.",
        unlockLevel: 8,
        level: 3,
        cost: 16,
      },
      {
        id: "s3",
        name: "Meteor",
        image: "/spells/counterspell.png",
        description: "Deals {magical damage * 2.2 + skill level * 40} damage to all enemies. Costs {50 - skill level * 2} MP.",
        unlockLevel: 15,
        level: 2,
        cost: 20,
      },
    ],
    stats: {
      physicalDamage: 82,
      magicalDamage: 298,
      critChance: 24,
      critDamage: 235,
      hp: 1280,
      mp: 525,
      physicalResistance: 11,
      magicalResistance: 24,
      speed: 128,
    },
  },
];

export const PLAYER_RESOURCES: PlayerResources = {
  ruby: 42,
  coin: 45680,
};

export const MAX_CHARACTER_LEVEL = 50;
export const MAX_SKILL_LEVEL = 10;
